const STRONG_CYAN = 'rgb(33, 206, 153)';
const BRIGHT_RED = 'rgb(244, 85, 49)';
const DARK_CYAN = 'rgb(14, 88, 65)';
const SOFT_CYAN = 'rgb(140, 237, 207)';
// const LIGHT_GRAY = 'rgb(240, 240, 240)';
const WHITE = 'rgb(255, 255, 255)';

const FILL = STRONG_CYAN;
const STROKE = WHITE;
const LINE_STROKE = STRONG_CYAN;
const SELECTED = BRIGHT_RED;
const SELECTED_FILL = BRIGHT_RED;
const SELECTED_STROKE = WHITE;
const LINE_SELECTED_STROKE = BRIGHT_RED;
const HOVERED = BRIGHT_RED;
const GROUP_SELECTED = BRIGHT_RED;
const COLOR_RANGE = [DARK_CYAN, SOFT_CYAN];

const DEFAULT_WAIT = 500;

export {
  FILL,
  STROKE,
  LINE_STROKE,
  SELECTED,
  SELECTED_FILL,
  SELECTED_STROKE,
  LINE_SELECTED_STROKE,
  HOVERED,
  GROUP_SELECTED,
  COLOR_RANGE,
  DEFAULT_WAIT,
};
